name: NewApp #FIXME

configs:
  Debug: debug
  Staging: release
  Release: release

options:
  # bundleIdPrefix: com.domain
  deploymentTarget:
    iOS: 13.0

packages:
  Networking:
    url: https://github.com/freshOS/Networking
    from: 0.3.4

targets:
  NewApp: #FIXME
    type: application
    platform: iOS
    sources:
      - path: Application
    dependencies:
      - package: Networking
    configFiles:
      Debug: Application/Configuration/Debug.xcconfig
      Staging: Application/Configuration/Staging.xcconfig
      Release: Application/Configuration/Release.xcconfig
    info:
      path: Application/Resources/Info.plist
      properties:
        ITSAppUsesNonExemptEncryption: false
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    postBuildScripts:
      - name: swiftlint
        script: |
                if [[ -f ./Mintfile ]] ; then
                  mint run swiftlint
                else
                  echo "error: Not exists Mintfile, Please run \"make mint\"."
                  exit 1
                fi
      # 為避免 undo history 被清除, 需要時再執行 mint run swiftformat . 
      # - name: SwiftFormat
      #   script: |
      #           if [[ -f ./Mintfile ]] ; then
      #             mint run swiftformat .
      #           else
      #             echo "error: Not exists Mintfile, Please run \"make mint\"."
      #             exit 1
      #           fi
    settings:
      base:
        # DEVELOPMENT_TEAM: SDDM52ZQBR  #FIXME
        CODE_SIGN_STYLE: Manual
        IPHONEOS_DEPLOYMENT_TARGET: 13.0
        SWIFT_VERSION: 5.0

        MARKETING_VERSION: 0.0.1
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1 # 1: iPhone, 2: iPad
        PRODUCT_NAME: $(APP_NAME)
        FRAMEWORK_SEARCH_PATHS: 
        - $(inherited)

      configs:
        Debug:
          CODE_SIGN_IDENTITY: Apple Development
          # DISPLAY_NAME_SUFFIX: _dev
          INFOPLIST_FILE: Application/Resources/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: com.domain.appName.dev
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Staging:
          CODE_SIGN_IDENTITY: Apple Distribution
          # DISPLAY_NAME_SUFFIX: _stg
          INFOPLIST_FILE: Application/Resources/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: com.domain.appName.stg
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: STAGING
        Release:
          CODE_SIGN_IDENTITY: Apple Distribution
          # DISPLAY_NAME_SUFFIX: 
          INFOPLIST_FILE: Application/Resources/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: com.domain.appName
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE

    scheme:
      testTargets:
      - ApplicationTests
      gatherCoverageData: false #不顯示在 scheme

  ApplicationTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ApplicationTests
